"""Migration message

Revision ID: 2d36a1563a4b
Revises: 
Create Date: 2021-12-09 12:33:14.403767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d36a1563a4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=True),
    sa.Column('profile_email', sa.String(length=100), nullable=True),
    sa.Column('profile_age', sa.String(length=100), nullable=True),
    sa.Column('profile_form', sa.String(length=100), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
