"""Remove skills content

Revision ID: 5741234a7414
Revises: c2501506b17f
Create Date: 2022-08-15 14:01:51.199910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5741234a7414'
down_revision = 'c2501506b17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'skills_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('skills_content', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
