"""Update database

Revision ID: 6dc0243fd3f1
Revises: c327b22bdc90
Create Date: 2021-12-09 16:15:43.459344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc0243fd3f1'
down_revision = 'c327b22bdc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skills_title', sa.String(length=100), nullable=True),
    sa.Column('skills_content', sa.Text(), nullable=True),
    sa.Column('skills_class', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    # ### end Alembic commands ###
