"""empty message

Revision ID: c2501506b17f
Revises: 6dc0243fd3f1
Create Date: 2022-04-04 15:26:15.516846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2501506b17f'
down_revision = '6dc0243fd3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_view_url', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('project_github_url', sa.Text(), nullable=True))
    op.drop_column('projects', 'project_detail')
    op.drop_column('projects', 'project_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_url', sa.TEXT(), nullable=True))
    op.add_column('projects', sa.Column('project_detail', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('projects', 'project_github_url')
    op.drop_column('projects', 'project_view_url')
    # ### end Alembic commands ###
