"""Chaneg name

Revision ID: c327b22bdc90
Revises: 2d36a1563a4b
Create Date: 2021-12-09 15:13:17.020567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c327b22bdc90'
down_revision = '2d36a1563a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('profile_from', sa.String(length=100), nullable=True))
    op.drop_column('profile', 'profile_form')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('profile_form', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('profile', 'profile_from')
    # ### end Alembic commands ###
